language: java
sudo: required
services:
  - docker

branches:
  - master

before_install:
  - echo TODO Setup Artifactory credentials
  - sudo apt-get update -qq

install:
  - echo TODO install debian package of CI Scripts.

script:
  - mvn -B clean install
  - |-
    docker build \
    --build-arg version="$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)" \
    --build-arg jar="$(mvn -q -Dexec.executable="echo" -Dexec.args='${jar.finalName}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec).jar" \
    -t simple-service:latest .
