language: java
sudo: required
services:
  - docker

branches:
  - master

before_install:
  - git config remote.origin.url https://${GH_TOKEN}@github.com/SwampUpMereMortals/simple-service.git
  - git config --global user.email "mere.mortal.ci@gmail.com"
  - git config --global user.name "Mere Mortal CI"
  - sudo su -c "echo -e \"deb https://${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}@meremortal.jfrog.io/meremortal/mortal-debian precise main\n\" >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - docker login -u "${ARTIFACTORY_USER}" -p "${ARTIFACTORY_PASSWORD}" https://meremortal-mortal-docker.jfrog.io

install:
  - sudo apt-get install ci-scripts --force-yes

script:
  - set -e
  - mvn -B clean install
  - export SERVICE_NAME=simple-service
  - export SERVICE_VERSION="$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)"
  - export JAR_NAME="$(mvn -q -Dexec.executable="echo" -Dexec.args='${jar.finalName}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec).jar"
  - docker build --build-arg version=${SERVICE_VERSION} --build-arg jar=${JAR_NAME} -t meremortal-mortal-docker.jfrog.io/${SERVICE_NAME}:${SERVICE_VERSION} .
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      set -e;
      echo "Conducting a version bump and publish to Artifactory." ;
      /opt/mere-mortals/swampup/publish-docker-image.sh ${SERVICE_NAME} ${SERVICE_VERSION};
      /opt/mere-mortals/swampup/increment-pom-version.sh;
    fi
